// описание экшнов
const constants = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_CART: 'SET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    INCREASE_COUNT: 'INCREASE_COUNT',
    DECREASE_COUNT: 'DECREASE_COUNT',
    SET_TOTAL_AMOUNT: 'SET_TOTAL_AMOUNT',
    CLEAR_CART: 'CLEAR_CART',
    SET_COUNTRY: 'SET_COUNTRY',
    SET_CITY: 'SET_CITY',
    CLEAR_CITY: 'CLEAR_CITY'

}

export default constants;
